services:
  app:
    container_name: widget-app
    build: .
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - node_modules/
    ports:
      - "3000:3000"
    command: ["npm", "run", "start"]
    restart: always
